version: '3.1'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "4317:4317"
    networks:
      - jaeger_net
    environment:
      - METRICS_STORAGE_TYPE=prometheus

  recipe_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    container_name: recipe_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - db_net
      - jaeger_net

  persistence-backend:
    depends_on:
      - recipe_db
    build:
      context: ../opentracing/persistence-service
    image: persistence_service
    container_name: persistence-service
    ports:
      - 8888:8888
    networks:
      - services_net
      - db_net
      - jaeger_net

  interaction-service:
    depends_on:
      - persistence-backend
    build:
      context: ../opentracing/user-interaction-service
    image: interaction-service
    container_name: interaction-service
    ports:
      - 8080:8080
    networks:
      - services_net
      - jaeger_net

networks:
  db_net:
    driver: bridge
  services_net:
    driver: bridge
  jaeger_net:
    driver: bridge